// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.gcoder.protobuf;

public interface RoleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zookeeper.protobuf.RoleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 所在服务器ID
   * </pre>
   *
   * <code>string serverId = 1;</code>
   */
  java.lang.String getServerId();
  /**
   * <pre>
   * 所在服务器ID
   * </pre>
   *
   * <code>string serverId = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerIdBytes();

  /**
   * <pre>
   * 登陆时间
   * </pre>
   *
   * <code>int64 loginTime = 2;</code>
   */
  long getLoginTime();

  /**
   * <pre>
   * 当前状态
   * </pre>
   *
   * <code>int32 state = 3;</code>
   */
  int getState();
}
